### ISSUE TITLE
Patch Application directly

### ISSUE THREAD

**Issue by jamesplease** [marionettejs/marionette.module#1]
`require('marionette.module').shim(Marionette.Application);`

^ That is unnecessary

`require('marionette.module');`

^ that is all that the API needs to be.

**Comment by samccone** [comment]
So you see this lib requiring marionette and then patching it? 
it is kinda nasty to monkey patch a lib silently, I prefer this explicit approach, however open to thoughts on either side of the fence.

**Comment by cmaher** [comment]
how about `require('marionette.module').shim(Marionette)`?

This will ensure that the proper Marionette is shimmed, and it will ensure that the shim will only be added to the application.

**Comment by samccone** [comment]
yeah I like that @cmaher ^

**Comment by jamesplease** [comment]
soundsgood2me

**Comment by jamesplease** [comment]
> change show the shim works

:P

**Comment by jasonLaster** [comment]
Lolz the inspector cries race condition. It's cool though...

**Comment by samccone** [comment]
im sorry :(
